Support script API
zariiii9003/pycanape pull request #1
Opened 2023-03-14 15:10 UTC by rookiepeng

Implement Scripting Functions:
bool ASAP3_EXPORT CALL_CONV  Asap3ExecuteScriptEx (TAsap3Hdl hdl, TModulHdl module, bool scriptFile, const char *script, TScriptHdl *hScript) 
  
bool ASAP3_EXPORT CALL_CONV  Asap3GetScriptState (TAsap3Hdl hdl, TScriptHdl hScript, TScriptStatus *scrstate, char *textBuffer, DWORD *sizeofbuffer)

bool ASAP3_EXPORT CALL_CONV  Asap3StopScript (TAsap3Hdl hdl, TScriptHdl hScript) 

bool ASAP3_EXPORT CALL_CONV  Asap3StartScript (TAsap3Hdl hdl, TScriptHdl hScript, char *Commandline=NULL, TModulHdl moduleHdl=ASAP3_INVALID_MODULE_HDL) 

bool ASAP3_EXPORT CALL_CONV  Asap3GetScriptResultValue (TAsap3Hdl hdl, TScriptHdl hScript, double *Value) 

bool ASAP3_EXPORT CALL_CONV  Asap3GetScriptResultString (TAsap3Hdl hdl, TScriptHdl hScript, char *resultString, DWORD *sizeofBuffer) 

bool ASAP3_EXPORT CALL_CONV  Asap3ReleaseScript (TAsap3Hdl hdl, TScriptHdl hScript)

2023-03-14 15:32 UTC, zariiii9003 requested changes
Thank you for your contribution, that looks very good!
Could you try to implement those changes? If that doesn't work, i will merge as it is.

2023-03-14 18:42 UTC, zariiii9003 commented on src/pycanape/script.py
> +            msg=c_buffer.value.decode(RC["ENCODING"])
Does the string buffer return the same text as the TScriptStatus enum names? If so, it would be redundant and we could just return the enum

2023-03-14 18:56 UTC, zariiii9003 commented on src/pycanape/script.py
> +        cnp_prototype.Asap3GetScriptResultValue(
```suggestion
        cnp_prototype.Asap3GetScriptResultString(
```

2023-03-14 18:57 UTC, zariiii9003 commented on src/pycanape/script.py
> +        cnp_prototype.Asap3GetScriptResultValue(
Asap3GetScriptResultString

2023-03-14 18:59 UTC, zariiii9003 commented
You should also add docstrings and make sure that the new functionality has an entry in the documentation.

2023-03-14 22:13 UTC, rookiepeng commented on src/pycanape/script.py
> +            msg=c_buffer.value.decode(RC["ENCODING"])
changed to return the enum only

2023-03-14 22:14 UTC, rookiepeng commented on src/pycanape/script.py
> +        cnp_prototype.Asap3GetScriptResultValue(
Thanks! This is a silly mistake

2023-03-17 17:01 UTC, rookiepeng commented
I think it is in good shape now. Please consider to merge. Thanks!

2023-03-17 17:38 UTC, zariiii9003 commented
The script class must be added to the documentation. [Here](https://pycanape--1.org.readthedocs.build/en/1/module.html) you can see the docs for your PR.

2023-03-19 14:27 UTC, zariiii9003 approved these changes
Looks good, thank you for your contribution and your patience.

2023-03-19 14:29 UTC, merged